config/routes.rb
Rails.application.routes.draw do
  resources :messages

  root 'messages#index'

end

app/models/message.rb
require 'mongoid_auto_inc'

class Message
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  field :text, type: String
  field :number, type: Integer

  has_many :child_messages, :class_name => 'Message'
  belongs_to :parent_message, :class_name => 'Message'

  auto_increment :number, scope: :parent_id

  def self.roots(page)
    self.where(parent_message_id: nil).page(page).per(10)
  end

  def root
    @_root ||= begin
                 current = self
                 loop do
                   return current if current.parent_message_id.nil?
                   current = current.parent_message
                 end
               end
  end

  def number_path
    @_number_path ||= begin
                        ids = []
                        current = self
                        loop do
                          ids << current.number
                          current = current.parent_message
                          break unless current
                        end
                        ids.reverse.join('.')
                      end
  end

  def child_message_list
    list= []
    child_messages.each do |m|
      list << m
      list = [list , m.child_message_list].flatten
    end
    list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
require 'blacklist'

class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.roots(params[:page])
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @child_list =  Kaminari.paginate_array( @message.child_message_list ).page(params[:page]).per(10)
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    attributes = message_params
    attributes['text'] = Blacklist.sanitize(attributes['text'])
    @message = Message.new(attributes)

    respond_to do |format|
      if @message.save
        format.html do
          destination = @message.parent_message ? @message.root  : messages_path
          redirect_to destination, notice: 'Message was successfully created.'
        end
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:text, :parent_message_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type.to_sym)} fade in") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>R7threads</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">R7Threads</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="https://coderbits.com/romeuhcf">About</a></li>
        <li><a href="https://coderbits.com/romeuhcf">Contact</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
      <%= flash_messages %>

  <%= yield %>

</div><!-- /.container -->

</body>
</html>

app/views/messages/_form.html.erb
<% message = Message.new %>
<%= form_for(message, html: {class: 'form-inline well'}) do |f| %>
  <%= f.hidden_field :parent_message_id %>
  <div class="form-group col-xs-4 ">
    <%= f.label :text, class: 'sr-only' %>
    <%= f.text_area :text, class: 'form-control entry' , placeholder: 'Message', rows: 3, cols: 30%>
  </div>
  <%= f.submit  value: 'Post'%>
<% end %>

app/views/messages/_message.html.erb
<p><%= ('&nbsp;' * 16 * ( message.number_path.split('.').size - 1 )).html_safe %><b><%= link_to message.number_path, message %></b>
<i><%= link_to message.created_at, message %> </i>
<%= message.text %> <span class="formholder"></span>
<input type="button" class="btn btn-sm reply" value="Reply" data-parent="<%= message.id %>" style="margin-left: 20px;">
</p>

app/views/messages/index.html.erb
<h1>Listing Messages</h1>

<%= render partial: 'form' %>

<ul class="messages">

  <% @messages.each do |message| %>
    <li>
    <b><%= link_to message.number_path, message %></b>
    <i><%= link_to message.created_at, message %> </i>
    <%= message.text %>
    </li>
  <% end %>
</ul>

<br>
<%= paginate @messages %>
<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<h3>Tópico <%= @message.text %> </h3>
<hr/>
<%= render partial: 'message', locals: {message: @message} %>
<hr/>
<%= render @child_list %>
<%= paginate @child_list %>
<template>
<%= render partial: 'form'%>
</template>